version: '3.8'

services:
  # TruthSeeker Backend
  truthseeker-backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=truthseeker
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MongoDB
  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=truthseeker
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    command: mongod --quiet

  # Nginx for frontend (optional - for local testing)
  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - truthseeker-backend
    restart: unless-stopped

volumes:
  mongo_data: